### PR TITLE
Adds optional active class to target element

### PR DESCRIPTION
**Pull request by jakemauer**
This adds rudimentary support for adding and removing an active class on the target element. My goal was to make it possible to use ember-pop-over for general purpose buttons and nav dropdowns where it's necessary to have an 'active' or 'pushed' state on the button itself. 

If this was already possible and I missed it, or this code isn't up to snuff I'm all ears. 

Thank you for all your work on this addon!

Example: 

```
<button id='my-button'>
{{#my-popover for='my-button' activeClassName='active'}}
  <ul>
     <li>Item 1</li>
    <li>Item 2</li>
</ul>
{{/my-popover}}
```

When you click on the button it should transform to `<button id='my-button' class='active'>` and 'active' will be removed when the popover hides.

### CODE REVIEW

**Comment by renatocarvalho** [comment]
This would be very good to have and useful!

**Comment by tim-evans** [comment]
Ooh! You can implement this using `onshow` and `onhide`. :)

**Comment by tim-evans** [comment]
This is supported using `onhide` and `onshow` as actions.

```htmlbars
<button id='my-button' class="{{if active 'active'}}>
{{#my-popover for='my-button' onshow=(action (mut active) true) onhide=(action (mut active) false)}}
  <ul>
     <li>Item 1</li>
    <li>Item 2</li>
</ul>
{{/my-popover}}
```

**Comment by tim-evans** [comment]
I'm don't want to support this; I'd prefer this to be done using the hooks I provided above. I can add documentation and a recipe for this pattern in the README.

**Comment by jakemauer** [comment]
Thanks Tim!

**Pull request closed without merging**
